#
# Makefile for Smack utilities.
# Generated by hand, as the Intelligent Designer intended.
#
# Copyright (c) 2007 Casey Schaufler <casey@schaufler-ca.com>
#

PROGRAMS = smackload smackcipso smackpolyport smackexec t

STATICLIB = libsmack.a

LIBSMACKOBJ = smackrecvmsg.o smackaccess.o setsmack.o getsmack.o smackenabled.o getsmackuser.o

CFLAGS+=-fPIC -L. -lsmack

default: ${PROGRAMS} ${STATICLIB} pam_smack.so

${PROGRAMS}: ${STATICLIB}

clean:
	rm -f ${PROGRAMS} ${STATICLIB} ${LIBSMACKOBJ}

libsmack.a: ${LIBSMACKOBJ}
	ar cr $@ ${LIBSMACKOBJ}

pam_smack.so: pam_smack.o ${LIBSMACKOBJ}
	$(CC) -fPIC -shared -o pam_smack.so pam_smack.o ${LIBSMACKOBJ} -lpam


