#
# Makefile for Smack utilities.
# Generated by hand, as the Intelligent Designer intended.
#
# Copyright (c) 2007 Casey Schaufler <casey@schaufler-ca.com>
#

PROGRAMS = smackload smackcipso smackpolyport

STATICLIB = libsmack.a

LIBSMACKSRC = smackrecvmsg.c smackaccess.c smackpolyport.c
LIBSMACKOBJ = smackrecvmsg.o smackaccess.o

default: ${PROGRAMS} ${STATICLIB}

clean:
	rm -f ${PROGRAMS} ${STATICLIB} ${LIBSMACKOBJ}

libsmack.a: ${LIBSMACKOBJ}
	ar cr $@ ${LIBSMACKOBJ}


